- POMPOM/POMPOM.xcodeproj/project.pbxproj
- POMPOM/POMPOM/Views/JeniView.swift
create jeni view in test branch
> create jeni view

- POMPOM/POMPOM.xcodeproj/project.pbxproj
- POMPOM/POMPOM/Views/GunView.swift
> GunView 추가

- POMPOM/POMPOM.xcodeproj/project.pbxproj
- POMPOM/POMPOM/Views/TimoView.swift
Find my message by comparing code changes!
> Timo's Test for PR

- POMPOM/POMPOM.xcodeproj/project.pbxproj
- POMPOM/POMPOM/Views/JeniView.swift
add jeniView file in realRealTest branch
> [ADD] Views/JeniView

- POMPOM/POMPOM.xcodeproj/project.pbxproj
- POMPOM/POMPOM/Views/DanaView.swift
> [ADD] danaview 생성

- POMPOM/POMPOM.xcodeproj/project.pbxproj
- POMPOM/POMPOM/Views/GunView.swift
> feat: GunView 추가

- POMPOM/POMPOM.xcodeproj/project.pbxproj
- POMPOM/POMPOM/Views/FelixView.swift
Felix 브렌치를 생성하여 FelixView를 생성하였습니다.
> [ADD] Felix View를 생성함.

- POMPOM/POMPOM.xcodeproj/project.pbxproj
- POMPOM/POMPOM/Views/JeniView2.swift
create jeni branch and add file JeniView2
> [ADD] create jenibranch

- POMPOM/POMPOM.xcodeproj/project.pbxproj
- POMPOM/POMPOM/UI/CoupleView/CoupleView.swift
- POMPOM/POMPOM/UI/CoupleView/SheetView.swift
* ColorPickerView의 frame으로 사용할 SheetView추가
* SheetView 통하여 CoupleView 안에 ColorPickerView 넣음
> Cloth picker view frame

- POMPOM/POMPOM/UI/CoupleView/ViewModel/CodeViewModel.swift
- CodeViewModel에서 Jeni의 채팅 기능 구현을 위해 getPartnerCode 로직을 구현
- UserDefaults에 partner_code라는 키로 로컬에도 저장
- 고민 없습니다.
- 없습니다.
- 없습니다.
> Jeni의 채팅을... 위하여!

- POMPOM/POMPOM.xcodeproj/project.pbxproj
- POMPOM/POMPOM/UI/SettingsView/SettingsView.swift
* 설정 화면 구현
* 연결 해지 로직은 추후 연결 필요
> [ADD]: SettingsView.swift - SettingsView 추가

- POMPOM/POMPOM.xcodeproj/project.pbxproj
- POMPOM/POMPOM/Models/Message.swift
- POMPOM/POMPOM/UI/ChatView/MessageBubbleView.swift
- POMPOM/POMPOM/UI/ChatView/MessageListView.swift
- POMPOM/POMPOM/UI/ChatView/TextFieldView.swift
> [ADD] : 채팅 모달 네트워킹 연결

- POMPOM/POMPOM/Networking/CodeManager.swift
- POMPOM/POMPOM/UI/CoupleView/CodeInputView.swift
- POMPOM/POMPOM/UI/CoupleView/CoupleView.swift
- POMPOM/POMPOM/UI/CoupleView/ViewModel/ClothViewModel.swift
- 상대방과 연결이 됐는지 boolean 값으로 UserDefaults에 저장
- 상대방과 연결된 경우 상대방 착장을 서버로부터 받아와서 CoupleView에 띄움
- nil
- nil
- logic
> [ADD] 코드로 상대방 데이터 불러오기 완료

- POMPOM/POMPOM/Networking/ClothesManager.swift
- 한 줄 PR입니다.
- addSnapShotListener 추가했습니다. (실시간 착장 반영을 위해)
- nil
- nil
> [FIX] ClothesManager load 메서드에 리스너 추가

- POMPOM/POMPOM/Models/Message.swift
- POMPOM/POMPOM/UI/ChatView/MessageListView.swift
- POMPOM/POMPOM/UI/ChatView/SlideModalView.swift
- POMPOM/POMPOM/UI/CoupleView/CoupleView.swift
> [FIX] : 모달 오류 수정

- POMPOM/POMPOM/UI/CoupleView/CoupleView.swift
> [FIX] : 옷 선택시 모달 컨트롤 완료

- POMPOM/POMPOM/Networking/CodeManager.swift
- POMPOM/POMPOM/UI/CoupleView/CodeInputView.swift
- ConnectionManagerError를 ConnectionManagerResultType으로 리팩토링
- Success 시에도 성공타입을 throws 할 수 있도록 수정
- 성공한 결과를 throws 하는 게 맞는지 고민
- 내용을 적어주세요.
- 없습니다.
> [FIX] 코드를 입력하지 않아도 연결된 화면으로 이동됨

- POMPOM/POMPOM/UI/CoupleView/CoupleView.swift
* 리셋 버튼 추가
* 아이폰 13 전 기종과 SE 에서 버튼 위치 확인 완료
사진
> [ADD]: 리셋 버튼 추가

- POMPOM/POMPOM/UI/ChatView/SlideModalView.swift
- 코멘트 모달의 기본 값 정정.
- 코멘트 모달의 오퍼시티 수정.
- 내용을 적어주세요.
- 내용을 적어주세요.
> 코멘트 모달에 기본값과 오퍼시티 수정

- POMPOM/POMPOM/UI/CoupleView/CoupleView.swift
- 초기화 버튼 이미지 수정
- 내용을 적어주세요.
- 내용을 적어주세요.
> 초기화 버튼 이미지 수정

- POMPOM/POMPOM/UI/ChatView/SlideModalView.swift
> [FIX] : 키보드 보일 시 모달 고정

- POMPOM/POMPOM.xcodeproj/project.pbxproj
- POMPOM/POMPOM/Models/Message.swift
- POMPOM/POMPOM/UI/ChatView/TextFieldView.swift
- POMPOM/POMPOM/Util/Extensions/hideKeyboard.swift
메시지에서 ! 쓰인 것들 전부 교체했습니다(timestamp는 예외)
> [FIX] : ! 제거했습니다

- POMPOM/POMPOM/UI/ClothPickerView/ColorGrid.swift
- POMPOM/POMPOM/UI/ClothPickerView/ViewModel/PickerViewModel.swift
[[DELETE] 프리셋 추가 버튼 제거](https://github.com/DeveloperAcademy-POSTECH/MC2-Team4-POMPOM/commit/4fb4d83360b1704147273b7ba811b4d7a563f012)
> [ADD] 개별 옷 삭제 연동 오류 해결

- POMPOM/POMPOM/UI/ClothPickerView/ClothPickerView.swift
- POMPOM/POMPOM/UI/ClothPickerView/ClothPickerViewModel.swift
- POMPOM/POMPOM/UI/CoupleView/CoupleView.swift
- #87 
- ClotePickerViewModel 의 핵심 로직들을 Combine 프레임워크를 활용해 리팩터링하였습니다.
- 버전 1.1 배포전 지속적인 QA 가 필요합니다.
- 핵심 기능의 경우 정상 작동함을 확인하였습니다.
> [REFACTOR] ClothPickerViewModel, ClothViewModel ->  Combine 코드 대체
